apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-claim-dynamic
spec:
  storageClassName: cloud-storage-efs
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi