apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-storage-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-052d5cc0aec18cecc # Unique to all EFS created
  directoryPerms: "700"
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic-cloud-class
provisioner: kubernetes.io/aws-ebs